name: flat
description: >-
  A simple, no dependency 🚀 way to take a nested Map and flatten it into a single depth Map.
  Based on Node.js `flat` package.

homepage: https://github.com/danilofuchs/flat
repository: https://github.com/danilofuchs/flat

version: 0.4.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.7

license: MIT
